# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

environment:
  global:
    RUST_VERSION: nightly-2020-02-21
    CRATE_NAME: elba

  matrix:
    # Testing other channels
    - TARGET: i686-pc-windows-msvc
      RUST_VERSION: nightly-2020-02-21
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: nightly-2020-02-21

install:
  - ps: >-
      If ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
        ren "C:\Program Files\Git\usr\bin\sh.exe" _sh.exe
        copy c:\msys64\mingw64\bin\mingw32-make.exe c:\msys64\mingw64\bin\make.exe
        $Env:PATH += ';C:\msys64\mingw64\bin;C:\msys64\usr\bin'
      } ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
        ren "C:\Program Files\Git\usr\bin\sh.exe" _sh.exe
        copy c:\msys64\mingw32\bin\mingw32-make.exe c:\msys64\mingw32\bin\make.exe
        $Env:PATH += ';C:\msys64\mingw32\bin;C:\msys64\usr\bin'
      }
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

test_script:
  # we don't run the "test phase" when doing deploys
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo build --target %TARGET% &&
      cargo build --target %TARGET% --release &&
      cargo test --target %TARGET% &&
      cargo test --target %TARGET% --release &&
      cargo run --target %TARGET% &&
      cargo run --target %TARGET% --release
    )

before_deploy:
  - cargo rustc --target %TARGET% --release --bin elba -- -C lto
  - ps: ci\before_deploy.ps1

deploy:
  artifact: /.*\.zip/
  auth_token:
    secure: nDfMGdntE2VUlSOMkb3OnEmSxz32U8WPCkErulaKRyykfs3w/JYKpWEKinPILuVU
  description: ''
  on:
    appveyor_repo_tag: true
  provider: GitHub

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    # Release tags
    - /^v?\d+\.\d+\.\d+.*$/
    - master

notifications:
  - provider: Email
    on_build_success: false

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
