[package]
name = "elba"
version = "0.1.0"
authors = ["David Cao <dcao@protonmail.com>"]
license = "MIT"

[dependencies]
clap = "2"
crossbeam = "0.4"
digest = { version = "0.7", features = ["std"]}
directories = "1"
failure = "0.1"
flate2 = "1.0"
git2 = "0.7"
indexmap = { version = "1", features = ["serde-1"] }
Inflector = "0.11"
itertools = "0.7"
nom = "4.0"
petgraph = "0.4"
reqwest = "0.8"
semver = { version = "0.9", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.7"
shell-escape = "0.1"
slog = { version = "2", features = ["max_level_trace", "release_max_level_warn"] }
slog-async = "2"
slog-term = "2"
symlink = "0.1"
tar = "0.4"
toml = "0.4"
url = "1.7"
url_serde = "0.2"
walkdir = "2"

[dev-dependencies]
lazy_static = "1"

[lib]
name = "elba"
path = "src/lib/lib.rs"

[[bin]]
name = "elba"
path = "src/bin/main.rs"
